### PR TITLE
Added The RypeNation

### PR DESCRIPTION
**Pull request by NicholasLAranda**

### CODE REVIEW

**Comment by ryan-shaw** [comment]
Do you have https?

**Comment by NicholasLAranda** [comment]
The domain is from NameCheap, we forward it to 142.44.241.180

How would we get https without paying for it?

**Comment by ryan-shaw** [comment]
letsencrypt

**Comment by NicholasLAranda** [comment]
Generating one now, stand by

**Comment by NicholasLAranda** [comment]
So I used EasyHTTPs because I'm using Node.js as my web server and LetsEncrypt only works with like Nginx and Apache.

I followed all the steps for addingtxt and ns entries to my domains DNS. I downloaded the certs. I'm trying to run some program they have but its all google translated from Chinese so it's not clear on what the error is that I'm getting and how to fix it.

Would you be willing to assist me over Discord some time?

RypeDub#7388

**Comment by ryan-shaw** [comment]
Unlikely, very busy. But will accept PR with HTTP.

**Pull request merged**
